// Firebase configuration
const firebaseConfig = {
    apiKey: "AIzaSyCmFOzpOnj56qPsJmOeH_fGbHfNaNMrKKI",
    authDomain: "lumi-configurator.firebaseapp.com",
    projectId: "lumi-configurator",
    storageBucket: "lumi-configurator.firebasestorage.app",
    messagingSenderId: "302539320691",
    appId: "1:302539320691:web:19917286b3519f66d4a906",
    measurementId: "G-YWNWB9RLKJ"
};

// Backend API base URL
const API_BASE_URL = 'http://43.205.185.170';

// Image galleries data
const imageGalleries = {
    'regular': [
        { id: 3, src: './assets/regular/2.png', name: '4 Touch' },
        { id: 1, src: './assets/regular/1.png', name: '2 Touch' },
    ],
    'customize': [
        { id: 1, src: './assets/icons/1.png', name: 'Icon 1' },
        { id: 2, src: './assets/icons/2.png', name: 'Icon 2' },
        { id: 3, src: './assets/icons/3.png', name: 'Icon 3' },
        { id: 4, src: './assets/icons/4.png', name: 'Icon 4' },
        { id: 5, src: './assets/icons/5.png', name: 'Icon 5' },
        { id: 6, src: './assets/icons/6.png', name: 'Icon 6' },
        { id: 7, src: './assets/icons/7.png', name: 'Icon 7' },
        { id: 8, src: './assets/icons/8.png', name: 'Icon 8' },
        { id: 9, src: './assets/icons/9.png', name: 'Icon 9' },
        { id: 10, src: './assets/icons/10.png', name: 'Icon 10' },
        { id: 11, src: './assets/icons/11.png', name: 'Icon 11' },
        { id: 12, src: './assets/icons/12.png', name: 'Icon 12' },
        { id: 13, src: './assets/icons/13.png', name: 'Icon 13' },
        { id: 14, src: './assets/icons/14.png', name: 'Icon 14' },
        { id: 15, src: './assets/icons/15.png', name: 'Icon 15' },
        { id: 16, src: './assets/icons/16.png', name: 'Icon 16' },
        { id: 17, src: './assets/icons/17.png', name: 'Icon 17' },
        { id: 18, src: './assets/icons/18.png', name: 'Icon 18' },
        { id: 19, src: './assets/icons/19.png', name: 'Icon 19' },
        { id: 20, src: './assets/icons/20.png', name: 'Icon 20' },
        { id: 21, src: './assets/icons/21.png', name: 'Icon 21' },
        { id: 22, src: './assets/icons/22.png', name: 'Icon 22' },
        { id: 23, src: './assets/icons/23.png', name: 'Icon 23' },
        { id: 24, src: './assets/icons/24.png', name: 'Icon 24' },
        { id: 25, src: './assets/icons/25.png', name: 'Icon 25' },
        { id: 26, src: './assets/icons/26.png', name: 'Icon 26' },
        { id: 27, src: './assets/icons/27.png', name: 'Icon 27' },
        { id: 28, src: './assets/icons/28.png', name: 'Icon 28' },
        { id: 29, src: './assets/icons/29.png', name: 'Icon 29' },
        { id: 30, src: './assets/icons/30.png', name: 'Icon 30' },
        { id: 31, src: './assets/icons/31.png', name: 'Icon 31' },
        { id: 32, src: './assets/icons/32.png', name: 'Icon 32' },
        { id: 33, src: './assets/icons/33.png', name: 'Icon 33' },
        { id: 34, src: './assets/icons/34.png', name: 'Icon 34' },
        { id: 35, src: './assets/icons/35.png', name: 'Icon 35' },
        { id: 36, src: './assets/icons/36.png', name: 'Icon 36' },
        { id: 37, src: './assets/icons/37.png', name: 'Icon 37' },
        { id: 38, src: './assets/icons/38.png', name: 'Icon 38' },
        { id: 39, src: './assets/icons/39.png', name: 'Icon 39' },
        { id: 40, src: './assets/icons/40.png', name: 'Icon 40' },
        { id: 41, src: './assets/icons/41.png', name: 'Icon 41' },
        { id: 42, src: './assets/icons/42.png', name: 'Icon 42' },
        { id: 43, src: './assets/icons/43.png', name: 'Icon 43' },
        { id: 44, src: './assets/icons/44.png', name: 'Icon 44' },
        { id: 45, src: './assets/icons/45.png', name: 'Icon 45' },
        { id: 46, src: './assets/icons/46.png', name: 'Icon 46' },
        { id: 47, src: './assets/icons/47.png', name: 'Icon 47' },
        { id: 48, src: './assets/icons/48.png', name: 'Icon 48' },
        { id: 49, src: './assets/icons/49.png', name: 'Icon 49' },
        { id: 50, src: './assets/icons/50.png', name: 'Icon 50' },
        { id: 51, src: './assets/icons/51.png', name: 'Icon 51' },
        { id: 52, src: './assets/icons/52.png', name: 'Icon 52' },
        { id: 53, src: './assets/icons/53.png', name: 'Icon 53' },
        { id: 54, src: './assets/icons/54.png', name: 'Icon 54' },
        { id: 55, src: './assets/icons/55.png', name: 'Icon 55' },
        { id: 56, src: './assets/icons/56.png', name: 'Icon 56' },
        { id: 57, src: './assets/icons/57.png', name: 'Icon 57' },
        { id: 58, src: './assets/icons/58.png', name: 'Icon 58' },
        { id: 59, src: './assets/icons/59.png', name: 'Icon 59' },
        { id: 60, src: './assets/icons/60.png', name: 'Icon 60' },
        { id: 61, src: './assets/icons/61.png', name: 'Icon 61' },
        { id: 62, src: './assets/icons/62.png', name: 'Icon 62' },
        { id: 63, src: './assets/icons/63.png', name: 'Icon 63' },
        { id: 64, src: './assets/icons/64.png', name: 'Icon 64' },
        { id: 65, src: './assets/icons/65.png', name: 'Icon 65' },
        { id: 66, src: './assets/icons/66.png', name: 'Icon 66' },
        { id: 67, src: './assets/icons/67.png', name: 'Icon 67' },
        { id: 68, src: './assets/icons/68.png', name: 'Icon 68' },
        { id: 69, src: './assets/icons/69.png', name: 'Icon 69' },
        { id: 70, src: './assets/icons/70.png', name: 'Icon 70' },
        { id: 71, src: './assets/icons/71.png', name: 'Icon 71' },
        { id: 72, src: './assets/icons/72.png', name: 'Icon 72' },
        { id: 73, src: './assets/icons/73.png', name: 'Icon 73' },
        { id: 74, src: './assets/icons/74.png', name: 'Icon 74' },
        { id: 75, src: './assets/icons/75.png', name: 'Icon 75' },
        { id: 76, src: './assets/icons/76.png', name: 'Icon 76' },
        { id: 77, src: './assets/icons/77.png', name: 'Icon 77' },
        { id: 78, src: './assets/icons/78.png', name: 'Icon 78' },
        { id: 79, src: './assets/icons/79.png', name: 'Icon 79' },
        { id: 80, src: './assets/icons/80.png', name: 'Icon 80' },
        { id: 81, src: './assets/icons/81.png', name: 'Icon 81' },
        { id: 82, src: './assets/icons/82.png', name: 'Icon 82' },
        { id: 83, src: './assets/icons/83.png', name: 'Icon 83' },
        { id: 84, src: './assets/icons/84.png', name: 'Icon 84' },
        { id: 85, src: './assets/icons/85.png', name: 'Icon 85' },
        { id: 86, src: './assets/icons/86.png', name: 'Icon 86' },
        { id: 87, src: './assets/icons/87.png', name: 'Icon 87' },
    ],
    'single-accessory': [
        { id: 1, src: './assets/1 model/1.png', name: 'MCB Switch' },
        { id: 2, src: './assets/1 model/2.png', name: 'Regulator' },
        { id: 3, src: './assets/1 model/3.png', name: '2-Pin Socket' },
        { id: 4, src: './assets/1 model/4.png', name: 'USB Port' }
    ],
    'double-accessory': [
        { id: 1, src: './assets/2 model/4.png', name: '3-Pin Socket' },
        { id: 2, src: './assets/2 model/5.png', name: 'Regulator' },
        { id: 3, src: './assets/2 model/6.png', name: 'USB Port' },
        { id: 4, src: './assets/2 model/1.png', name: 'Blank' }
    ]
};

const sampleImages = [
    { id: 'regular', src: './assets/img/1.png', name: 'Regular' },
    { id: 'customize', src: './assets/img/4.png', name: 'Customize' },
    { id: 'single-accessory', src: './assets/img/3.png', name: 'Single Accessory' },
    { id: 'double-accessory', src: './assets/img/2.png', name: '2 Model Accessory' }
];